### ISSUE TITLE
Does not work with binary files.

### ISSUE THREAD

**Issue by ablundgren** [mike10004/concatenate-maven-plugin#1] opened 2018-12-10 23:53 UTC
If you split a binary file with:
split -b 200 binary.file
and then
cat x* > binary.file.out
and run
md5sum binary.file binary.file.out 
they are the same.

The doing the same with the plugin does not result in the same md5sum.

**Comment by mike10004** [comment] 2018-12-11 17:09
Thanks for reporting the issue. I have confirmed the unexpected behavior you describe. What is happening, I think, is that the filesystem does not provide a listing of a directory's files in the order that is expected, so the output file contains all of the parts but not in the right order.

As a workaround, you can list the files explicitly, like this:

    <execution>
        <id>binary-files-test</id>
        <phase>process-test-resources</phase>
        <goals>
            <goal>cat</goal>
        </goals>
        <configuration>
            <sources>
                <fileset>
                    <directory>${project.basedir}/src/test/input</directory>
                    <includes>
                        <include>bin/xaa</include>
                        <include>bin/xab</include>
                        <include>bin/xac</include>
                        <include>bin/xad</include>
                        <include>bin/xae</include>
                    </includes>
                </fileset>
            </sources>
            <outputFile>${BinaryFilesTest.outputFile}</outputFile>
        </configuration>
    </execution>

...instead of using a wildcard pattern like `<include>bin/x*</include>`.

Being able to use the wildcard pattern is a feature I would like to support, though, so I will try to think of a way to do that.

P.S. I don't think the problem is that the files are binary -- I think it would probably concatenate text files in an unpredictable order too.

**Comment by mike10004** [comment] 2018-12-11 19:50
I released a fix for this as of commit af0a7cd4236e88f6d81f5565b444c101c442d2b8. It be available as version 0.4 when it makes its way through the Sonatype queue. Use the `<sort>alphabetical</sort>` within your `<fileset>` element to sort the included files alphabetically. (This is the behavior that the shell induces when you execute `cat x* > binary.file.out`.)

**Closed as completed by mike10004** 2018-12-11 19:50 UTC
Labels: bug

**Comment by ablundgren** [comment] 2018-12-11 20:12
Awesome!  I will give it a try.  Thank you for your quick response!

**Comment by ablundgren** [comment] 2018-12-11 20:29
> As a workaround, you can list the files explicitly, like this:
> 

I was able to confirm that this does fix the issue as well.
